//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class ActionQueue : ICleanable
{
	public List<PrioritizedAction> actions = new List<PrioritizedAction>();


	/* assumes that other references to actions are responsibly cleared */ 
	public void Clean() {
		actions.Clear ();
	}

	public void Execute() {
		actions.Sort ();
		foreach (PrioritizedAction pa in actions) {
			pa.action();
		}
	}
	
	public int Count() {
		return actions.Count;
	}


	/* returns the created prioritized action for later removal */
	public PrioritizedAction AddAction(int pPriority, Action pCallback) {
		PrioritizedAction pa = new PrioritizedAction (pPriority, pCallback);
		pa.action = pCallback;
		pa.priority = pPriority;
		AddAction (pa);
		return pa; 
	}

	public PrioritizedAction AddAction(PrioritizedAction pPa) {
		actions.Add (pPa);
		return pPa;
	}


	public void RemoveAction(PrioritizedAction pPrioritizedAction) {
		actions.Remove (pPrioritizedAction);
	}

}


