//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class CoRoQueue<T> 
{
	public List<PrioritizedCoRo<T>> actions;


	/* assumes that other references to actions are responsibly cleared */ 

	public CoRoQueue() {
		Utils.print ("making coroq");
		actions = new List<PrioritizedCoRo<T>>();
	}
	public void Clean() {
		actions.Clear ();
	}

	public int Count() {
		return actions.Count;
	}

	public void Execute(T userdata) {
		actions.Sort ();
		foreach (PrioritizedCoRo<T> cr in actions) {
			cr.Execute(userdata);
		}
	}

	/* returns the created prioritized action for later removal */
	public PrioritizedCoRo<T> AddCoRo(int pPriority,Func<T, IEnumerable>  pCoRo, Action pCleanup) {
		PrioritizedCoRo<T> newPCoRo = new PrioritizedCoRo<T> (pPriority, pCoRo, pCleanup);
		AddCoRo (newPCoRo);
		return newPCoRo; 
	}

	public PrioritizedCoRo<T> AddCoRo(PrioritizedCoRo<T> pCoRo) {
		Utils.print ("adding coro");
		actions.Add (pCoRo);
		return pCoRo;
	}


	public void RemoveCoRo(PrioritizedCoRo<T> pPrioritizedCoRo) {
		Utils.print ("killing coro");
		actions.Remove (pPrioritizedCoRo);
	}

}


