//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class PrioritizedFunc<TIn, TOut> : IComparable {
	public Func<TIn, TOut> func;
	public float priority;
	public int CompareTo(object pTarget) {
		return this.priority.CompareTo ((pTarget as PrioritizedFunc<TIn, TOut>).priority);
	}
	public void Clean() {
		func = null;
	}
}


