//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

public class PrioritizedCoRo<T> : IComparable {
	public Func<T, IEnumerable> coRo;
	public Action cleanupFunc;
	public float priority = 0.0f;

	public PrioritizedCoRo(float pPriority, Func<T, IEnumerable>  pCoRo, Action pCleanupFunc) {
		coRo = pCoRo;
		cleanupFunc = pCleanupFunc;
		priority = pPriority;
	
	}
	public int CompareTo(object pTarget) {
		return this.priority.CompareTo ((pTarget as PrioritizedCoRo<T>).priority);
	}
	public void Clean() {
		if (cleanupFunc != null) {
			cleanupFunc ();
			cleanupFunc = null;
		}
		coRo = null;
	}
	public IEnumerable Execute(T userdata) {
		return coRo(userdata);
	}
}


