//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class PrioritizedAction : IComparable {
	public Action action;
	public float priority;
	public PrioritizedAction(float pPriority, Action pAction) {
		action = pAction;
		priority = pPriority;
	}
	public int CompareTo(object pTarget) {
		return this.priority.CompareTo ((pTarget as PrioritizedAction).priority);
	}
	public void Clean() {
		action = null;
	}
}


